- id: f516c1341f0f634c
  type: mqtt-broker
  name: noderedrt
  broker: 192.168.100.112
  port: 1883
  clientid: noderedrt
  autoConnect: true
  usetls: false
  protocolVersion: 4
  keepalive: 60
  cleansession: true
  autoUnsubscribe: true
  birthTopic: ''
  birthQos: '0'
  birthRetain: 'false'
  birthPayload: ''
  birthMsg: {}
  closeTopic: ''
  closeQos: '0'
  closeRetain: 'false'
  closePayload: ''
  closeMsg: {}
  willTopic: ''
  willQos: '0'
  willRetain: 'false'
  willPayload: ''
  willMsg: {}
  userProps: ''
  sessionExpiry: ''
- id: 68fb8d742e5053db
  type: ui-base
  name: Live Equipments
  path: /dashboard
  appIcon: ''
  includeClientData: true
  acceptsClientConfig:
    - ui-notification
    - ui-control
    - ui-form
    - ui-text-input
    - ui-number-input
    - ui-file-input
    - ui-button
    - ui-button-group
    - ui-dropdown
    - ui-radio-group
    - ui-slider
    - ui-switch
    - ui-text
    - ui-table
    - ui-chart
    - ui-gauge
    - ui-audio
    - ui-markdown
    - ui-template
    - ui-progress
  showPathInSidebar: false
  headerContent: dashboard
  navigationStyle: icon
  titleBarStyle: fixed
  showReconnectNotification: true
  notificationDisplayTime: '3'
  showDisconnectNotification: true
  allowInstall: false
- id: ca81bb608c015a0d
  type: ui-theme
  name: Default Theme
  colors:
    surface: '#ffffff'
    primary: '#0094ce'
    bgPage: '#eeeeee'
    groupBg: '#ffffff'
    groupOutline: '#cccccc'
  sizes:
    density: default
    pagePadding: 8px
    groupGap: 8px
    groupBorderRadius: 2px
    widgetGap: 8px
- id: 5287a3b059e7b4ce
  type: ui-page
  name: Arborescence
  ui: 68fb8d742e5053db
  path: /tree
  icon: file-tree
  layout: tabs
  theme: ca81bb608c015a0d
  breakpoints:
    - name: Default
      px: '0'
      cols: '3'
    - name: Tablet
      px: '576'
      cols: '6'
    - name: Small Desktop
      px: '768'
      cols: '9'
    - name: Desktop
      px: '1024'
      cols: '12'
  order: 3
  className: ''
  visible: 'true'
  disabled: 'false'
- id: 71ccb6fab20261e2
  type: ui-page
  name: Visualisation
  ui: 68fb8d742e5053db
  path: /view
  icon: eye
  layout: tabs
  theme: ca81bb608c015a0d
  breakpoints:
    - name: Default
      px: '0'
      cols: '3'
    - name: Tablet
      px: '576'
      cols: '6'
    - name: Small Desktop
      px: '768'
      cols: '9'
    - name: Desktop
      px: '1024'
      cols: '12'
  order: 1
  className: ''
  visible: 'true'
  disabled: 'false'
- id: 53fb0eee68c8f320
  type: ui-group
  name: Usines
  page: 5287a3b059e7b4ce
  width: 6
  height: 1
  order: 1
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 1669fa4fe2f204a0
  type: ui-group
  name: Visualisation
  page: 71ccb6fab20261e2
  width: 6
  height: 1
  order: 1
  showTitle: false
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: dd968c6d9fd51ce8
  type: ui-group
  name: Lignes
  page: 5287a3b059e7b4ce
  width: 6
  height: 1
  order: 2
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: e003b21feb885c70
  type: ui-group
  name: Equipements
  page: 5287a3b059e7b4ce
  width: 6
  height: 1
  order: 3
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 72650b0750e04cb4
  type: ui-group
  name: Composants
  page: 5287a3b059e7b4ce
  width: 6
  height: 1
  order: 5
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 78fc4d50f5e2bcc1
  type: ui-group
  name: Materiels
  page: 5287a3b059e7b4ce
  width: 6
  height: 1
  order: 4
  showTitle: true
  className: ''
  visible: true
  disabled: 'false'
  groupType: default
- id: 297c38d08e523a55
  type: ui-page
  name: Listes
  ui: 68fb8d742e5053db
  path: /list
  icon: format-list-bulleted-square
  layout: tabs
  theme: ca81bb608c015a0d
  breakpoints:
    - name: Default
      px: '0'
      cols: '3'
    - name: Tablet
      px: '576'
      cols: '6'
    - name: Small Desktop
      px: '768'
      cols: '9'
    - name: Desktop
      px: '1024'
      cols: '12'
  order: 2
  className: ''
  visible: 'true'
  disabled: 'false'
- id: c605809a8fe63a3b
  type: ui-group
  name: Listes
  page: 297c38d08e523a55
  width: '12'
  height: 1
  order: 1
  showTitle: false
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 71289f771ef25fc5
  type: influxdb
  hostname: 127.0.0.1
  port: 8086
  protocol: http
  database: database
  name: spi influxdb
  usetls: false
  tls: ''
  influxdbVersion: '2.0'
  url: 'http://192.168.100.113:8086'
  timeout: 10
  rejectUnauthorized: false
- id: 54e5153d8ee4c680
  type: ui-group
  name: Alertes
  page: 5287a3b059e7b4ce
  width: 6
  height: 1
  order: 6
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: cc92819045cc90af
  type: ui-group
  name: Programmateurs
  page: 5287a3b059e7b4ce
  width: 6
  height: 1
  order: 7
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 1ac335c1e0a24a11
  type: ui-page
  name: Système
  ui: 68fb8d742e5053db
  path: /system
  icon: cog
  layout: tabs
  theme: ca81bb608c015a0d
  breakpoints:
    - name: Default
      px: '0'
      cols: '3'
    - name: Tablet
      px: '576'
      cols: '6'
    - name: Small Desktop
      px: '768'
      cols: '9'
    - name: Desktop
      px: '1024'
      cols: '12'
  order: 4
  className: ''
  visible: 'true'
  disabled: 'false'
- id: 18e387e2011da847
  type: ui-group
  name: Système
  page: 1ac335c1e0a24a11
  width: 6
  height: 1
  order: 1
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: dc73b5e0cedbb3eb
  type: ui-group
  name: Firmware OPTA
  page: 1ac335c1e0a24a11
  width: 6
  height: 1
  order: 2
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
