- id: f516c1341f0f634c
  type: mqtt-broker
  name: mqtt
  broker: mqtt
  port: 1883
  clientid: noderedcompose
  autoConnect: true
  usetls: false
  protocolVersion: 4
  keepalive: 60
  cleansession: true
  autoUnsubscribe: true
  birthTopic: ''
  birthQos: '0'
  birthRetain: 'false'
  birthPayload: ''
  birthMsg: {}
  closeTopic: ''
  closeQos: '0'
  closeRetain: 'false'
  closePayload: ''
  closeMsg: {}
  willTopic: ''
  willQos: '0'
  willRetain: 'false'
  willPayload: ''
  willMsg: {}
  userProps: ''
  sessionExpiry: ''
- id: 68fb8d742e5053db
  type: ui-base
  name: Live Equipments
  path: /dashboard
  appIcon: /icon.png
  includeClientData: true
  acceptsClientConfig:
    - ui-notification
    - ui-control
    - ui-form
    - ui-text-input
    - ui-number-input
    - ui-file-input
    - ui-button
    - ui-button-group
    - ui-dropdown
    - ui-radio-group
    - ui-slider
    - ui-switch
    - ui-text
    - ui-table
    - ui-chart
    - ui-gauge
    - ui-audio
    - ui-markdown
    - ui-template
    - ui-progress
  showPathInSidebar: false
  headerContent: none
  navigationStyle: none
  titleBarStyle: hidden
  showReconnectNotification: true
  notificationDisplayTime: '3'
  showDisconnectNotification: true
  allowInstall: false
- id: ca81bb608c015a0d
  type: ui-theme
  name: Default Theme
  colors:
    surface: '#ffffff'
    primary: '#0094ce'
    bgPage: '#eeeeee'
    groupBg: '#ffffff'
    groupOutline: '#cccccc'
  sizes:
    density: default
    pagePadding: 6px
    groupGap: 8px
    groupBorderRadius: 4px
    widgetGap: 8px
- id: 5287a3b059e7b4ce
  type: ui-page
  name: Arborescence
  ui: 68fb8d742e5053db
  path: /tree
  icon: file-tree
  layout: notebook
  theme: ca81bb608c015a0d
  breakpoints:
    - name: Default
      px: '0'
      cols: '3'
    - name: Tablet
      px: '576'
      cols: '6'
    - name: Small Desktop
      px: '768'
      cols: '9'
    - name: Desktop
      px: '1024'
      cols: '12'
  order: 6
  className: ''
  visible: 'false'
  disabled: 'false'
- id: 71ccb6fab20261e2
  type: ui-page
  name: Détail
  ui: 68fb8d742e5053db
  path: /detail
  icon: magnify
  layout: notebook
  theme: ca81bb608c015a0d
  breakpoints:
    - name: Default
      px: '0'
      cols: '3'
    - name: Tablet
      px: '576'
      cols: '6'
    - name: Small Desktop
      px: '768'
      cols: '9'
    - name: Desktop
      px: '1024'
      cols: '12'
  order: 4
  className: ''
  visible: 'false'
  disabled: 'false'
- id: 1669fa4fe2f204a0
  type: ui-group
  name: Détail
  page: 71ccb6fab20261e2
  width: '6'
  height: 1
  order: 1
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 297c38d08e523a55
  type: ui-page
  name: Listes
  ui: 68fb8d742e5053db
  path: /list
  icon: format-list-bulleted-square
  layout: notebook
  theme: ca81bb608c015a0d
  breakpoints:
    - name: Default
      px: '0'
      cols: '3'
    - name: Tablet
      px: '576'
      cols: '6'
    - name: Small Desktop
      px: '768'
      cols: '9'
    - name: Desktop
      px: '1024'
      cols: '12'
  order: 5
  className: ''
  visible: 'false'
  disabled: 'false'
- id: c605809a8fe63a3b
  type: ui-group
  name: Listes
  page: 297c38d08e523a55
  width: '12'
  height: 1
  order: 1
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 71289f771ef25fc5
  type: influxdb
  hostname: 127.0.0.1
  port: 8086
  protocol: http
  database: database
  name: influxdb
  usetls: false
  tls: ''
  influxdbVersion: '2.0'
  url: 'http://influxdb:8086'
  timeout: 10
  rejectUnauthorized: false
- id: 1ac335c1e0a24a11
  type: ui-page
  name: Système
  ui: 68fb8d742e5053db
  path: /system
  icon: cog
  layout: notebook
  theme: ca81bb608c015a0d
  breakpoints:
    - name: Default
      px: '0'
      cols: '3'
    - name: Tablet
      px: '576'
      cols: '6'
    - name: Small Desktop
      px: '768'
      cols: '9'
    - name: Desktop
      px: '1024'
      cols: '12'
  order: 8
  className: ''
  visible: false
  disabled: false
- id: 18e387e2011da847
  type: ui-group
  name: Application
  page: 1ac335c1e0a24a11
  width: '6'
  height: 1
  order: 1
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: dc73b5e0cedbb3eb
  type: ui-group
  name: Firmware OPTA
  page: 1ac335c1e0a24a11
  width: '6'
  height: 1
  order: 3
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: a19160517715b70b
  type: ui-page
  name: Maintenance
  ui: 68fb8d742e5053db
  path: /alert
  icon: wrench
  layout: notebook
  theme: ca81bb608c015a0d
  breakpoints:
    - name: Default
      px: '0'
      cols: '3'
    - name: Tablet
      px: '576'
      cols: '6'
    - name: Small Desktop
      px: '768'
      cols: '9'
    - name: Desktop
      px: '1024'
      cols: '12'
  order: 2
  className: ''
  visible: 'false'
  disabled: 'false'
- id: ab8ef19cd1ae9d09
  type: ui-group
  name: Maintenance
  page: a19160517715b70b
  width: '6'
  height: 1
  order: 1
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 64fe17ae4a406472
  type: ui-page
  name: Authentification
  ui: 68fb8d742e5053db
  path: /auth
  icon: login
  layout: notebook
  theme: ca81bb608c015a0d
  breakpoints:
    - name: Default
      px: '0'
      cols: '3'
    - name: Tablet
      px: '576'
      cols: '6'
    - name: Small Desktop
      px: '768'
      cols: '9'
    - name: Desktop
      px: '1024'
      cols: '12'
  order: 1
  className: ''
  visible: true
  disabled: false
- id: 3c952a83cfc8f302
  type: ui-group
  name: Authentification
  page: 64fe17ae4a406472
  width: '6'
  height: 1
  order: 1
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 9d9e19b688919599
  type: ui-group
  name: Arborescence
  page: 5287a3b059e7b4ce
  width: '6'
  height: 1
  order: 1
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 4d7d40fad3a281d3
  type: ui-page
  name: Programmes
  ui: 68fb8d742e5053db
  path: /period
  icon: clock
  layout: notebook
  theme: ca81bb608c015a0d
  breakpoints:
    - name: Default
      px: '0'
      cols: '3'
    - name: Tablet
      px: '576'
      cols: '6'
    - name: Small Desktop
      px: '768'
      cols: '9'
    - name: Desktop
      px: '1024'
      cols: '12'
  order: 3
  className: ''
  visible: 'false'
  disabled: 'false'
- id: 09b574b24dc3ba17
  type: ui-group
  name: Programmes
  page: 4d7d40fad3a281d3
  width: 6
  height: 1
  order: 1
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: ed8b7656d516b26d
  type: ui-page
  name: Utilisateurs
  ui: 68fb8d742e5053db
  path: /users
  icon: account
  layout: notebook
  theme: ca81bb608c015a0d
  breakpoints:
    - name: Default
      px: '0'
      cols: '3'
    - name: Tablet
      px: '576'
      cols: '6'
    - name: Small Desktop
      px: '768'
      cols: '9'
    - name: Desktop
      px: '1024'
      cols: '12'
  order: 7
  className: ''
  visible: 'false'
  disabled: 'false'
- id: e9c7dc11bf2e5dfb
  type: ui-group
  name: Ajouter un utilisateur
  page: ed8b7656d516b26d
  width: '6'
  height: 1
  order: 3
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 71bafeee3e662114
  type: ui-group
  name: Liste des utilisateurs
  page: ed8b7656d516b26d
  width: 6
  height: 1
  order: 1
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: a20f184b0fc93e49
  type: ui-group
  name: Modifier un utilisateur
  page: ed8b7656d516b26d
  width: 6
  height: 1
  order: 2
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 0e1f5538e0c5b139
  type: ui-group
  name: Import / Export
  page: ed8b7656d516b26d
  width: 6
  height: 1
  order: 4
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: a8d6d74266e4b8d2
  type: ui-group
  name: Arborescence
  page: 1ac335c1e0a24a11
  width: 6
  height: 1
  order: 2
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 8775814af2fc0b33
  type: telegram bot
  botname: telegram
  usernames: ''
  chatids: '${OPTA_TELEGRAM_CHAT}'
  baseapiurl: ''
  testenvironment: false
  updatemode: polling
  pollinterval: 300
  usesocks: false
  sockshost: ''
  socksprotocol: socks5
  socksport: 6667
  socksusername: anonymous
  sockspassword: ''
  bothost: ''
  botpath: ''
  localbothost: 0.0.0.0
  localbotport: 8443
  publicbotport: 8443
  privatekey: ''
  certificate: ''
  useselfsignedcertificate: false
  sslterminated: false
  verboselogging: false
