- id: f516c1341f0f634c
  type: mqtt-broker
  name: noderedrt
  broker: 192.168.100.112
  port: 1883
  clientid: noderedrt
  autoConnect: true
  usetls: false
  protocolVersion: 4
  keepalive: 60
  cleansession: true
  autoUnsubscribe: true
  birthTopic: ''
  birthQos: '0'
  birthRetain: 'false'
  birthPayload: ''
  birthMsg: {}
  closeTopic: ''
  closeQos: '0'
  closeRetain: 'false'
  closePayload: ''
  closeMsg: {}
  willTopic: ''
  willQos: '0'
  willRetain: 'false'
  willPayload: ''
  willMsg: {}
  userProps: ''
  sessionExpiry: ''
- id: 68fb8d742e5053db
  type: ui-base
  name: SPI Live Equipments
  path: /dashboard
  appIcon: ''
  includeClientData: true
  acceptsClientConfig:
    - ui-notification
    - ui-control
  showPathInSidebar: false
  headerContent: dashboard
  navigationStyle: icon
  titleBarStyle: fixed
  showReconnectNotification: true
  notificationDisplayTime: 1
  showDisconnectNotification: true
  allowInstall: false
- id: ca81bb608c015a0d
  type: ui-theme
  name: Default Theme
  colors:
    surface: '#ffffff'
    primary: '#0094ce'
    bgPage: '#eeeeee'
    groupBg: '#ffffff'
    groupOutline: '#cccccc'
  sizes:
    density: default
    pagePadding: 12px
    groupGap: 12px
    groupBorderRadius: 4px
    widgetGap: 12px
- id: 5287a3b059e7b4ce
  type: ui-page
  name: Arborescence
  ui: 68fb8d742e5053db
  path: /tree
  icon: file-tree
  layout: notebook
  theme: ca81bb608c015a0d
  breakpoints:
    - name: Default
      px: '0'
      cols: '3'
    - name: Tablet
      px: '576'
      cols: '6'
    - name: Small Desktop
      px: '768'
      cols: '9'
    - name: Desktop
      px: '1024'
      cols: '12'
  order: 2
  className: ''
  visible: 'true'
  disabled: 'false'
- id: 71ccb6fab20261e2
  type: ui-page
  name: Visualisation
  ui: 68fb8d742e5053db
  path: /view
  icon: eye
  layout: notebook
  theme: ca81bb608c015a0d
  breakpoints:
    - name: Default
      px: '0'
      cols: '3'
    - name: Tablet
      px: '576'
      cols: '6'
    - name: Small Desktop
      px: '768'
      cols: '9'
    - name: Desktop
      px: '1024'
      cols: '12'
  order: 1
  className: ''
  visible: 'true'
  disabled: 'false'
- id: 53fb0eee68c8f320
  type: ui-group
  name: Gestion de site
  page: 5287a3b059e7b4ce
  width: 6
  height: 1
  order: 1
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 1669fa4fe2f204a0
  type: ui-group
  name: Selection
  page: 71ccb6fab20261e2
  width: 6
  height: 1
  order: 1
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: dd968c6d9fd51ce8
  type: ui-group
  name: Gestion de ligne
  page: 5287a3b059e7b4ce
  width: 6
  height: 1
  order: 2
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: e003b21feb885c70
  type: ui-group
  name: Gestion d'équipement
  page: 5287a3b059e7b4ce
  width: 6
  height: 1
  order: 3
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 72650b0750e04cb4
  type: ui-group
  name: Gestion de composant
  page: 5287a3b059e7b4ce
  width: 6
  height: 1
  order: 5
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
- id: 78fc4d50f5e2bcc1
  type: ui-group
  name: Gestion de materiel
  page: 5287a3b059e7b4ce
  width: 6
  height: 1
  order: 4
  showTitle: true
  className: ''
  visible: 'true'
  disabled: 'false'
  groupType: default
