version: "3.8" 
services: 
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: unless-stopped
    environment:
      DOCKER_MOSQUITTO_USERNAME: ${DOCKER_MOSQUITTO_USERNAME}
      DOCKER_MOSQUITTO_PASSWORD: ${DOCKER_MOSQUITTO_PASSWORD}
      DOCKER_MOSQUITTO_CONFIG: |-
        allow_anonymous false
        listener 1883
        persistence true
        password_file mosquitto/config/mosquitto.pass
        persistence_location /mosquitto/data/
    command: 
      - /bin/sh
      - -c
      - |
        cf="/mosquitto/config/mosquitto.conf"
        pf="/mosquitto/config/mosquitto.pass"
        if [ ! -f $$cf ]; then
          echo "> Creating config file $$cf"
          echo -n "$$DOCKER_MOSQUITTO_CONFIG" > $$cf
        else
          echo "> Found config file $$cf"
        fi
        cat $$cf
        echo " "
        if [ ! -f $$pf ]; then
          echo "> Creating password file"
          touch $$pf
          chown mosquitto:mosquitto $$pf
          chmod 600 $$pf
          /usr/bin/mosquitto_passwd -b $$pf $$DOCKER_MOSQUITTO_USERNAME $$DOCKER_MOSQUITTO_PASSWORD
        fi
        echo "> Running Eclipse-Mosquitto MQTT"
        /usr/sbin/mosquitto -c $$cf
    ports:
      - 1883:1883
      #- 8883:8883
      #- 9001:9001
    networks:
      - optanet 
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      test: mosquitto_sub -u $$DOCKER_MOSQUITTO_USERNAME -P $$DOCKER_MOSQUITTO_PASSWORD -t '$$SYS/#' -C 1 -i healthcheck -W 3
      interval: 10s
      timeout: 10s
      retries: 3   
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: optaequipments
      DOCKER_INFLUXDB_INIT_BUCKET: state
    ports:
      - 8086:8086
    networks:
      - optanet
    volumes:
      - influxdb_etc:/etc/influxdb2
      - influxdb_lib:/var/lib/influxdb2
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
      DOCKER_NODERED_USERNAME: ${DOCKER_NODERED_USERNAME}
      DOCKER_NODERED_PASSWORD: ${DOCKER_NODERED_PASSWORD}
      DOCKER_NODERED_SECRET: ${DOCKER_NODERED_SECRET}
      NODE_RED_ENABLE_PROJECTS: true
      TZ: Europe/Paris
      DOCKER_NODERED_CONFIG: |-
        module.exports = {
          flowFile: 'flows.json',
          credentialSecret: process.env.DOCKER_NODERED_SECRET,
          flowFilePretty: true,
          adminAuth: {
              type: 'credentials',
              users: [{
                  username: process.env.DOCKER_NODERED_USERNAME,
                  password: process.env.DOCKER_NODERED_PASSWORD,
                  permissions: '*'
              }],
              sessionExpiryTime : 86400
          },
          httpAdminRoot: '/admin',
          httpNodeRoot: '/',
          runtimeState: { enabled: false, ui: false, },
          logging: { console: { level: 'warn', metrics: false, audit: false } },
          contextStorage: { default: { module: 'localfilesystem' }, memoryOnly: { module: 'memory' }, },
          exportGlobalContextKeys: false,
          externalModules: { },
          editorTheme: {
              palette: { },
              projects: { enabled: true, workflow: { mode: 'manual' } },
              codeEditor: { lib: 'monaco', options: { } },
              markdownEditor: { mermaid: { enabled: true } },
          },
          functionExternalModules: true,
          functionTimeout: 0,
          functionGlobalContext: { },
          ui: { path: '' },
          debugUseColors: true,
          debugMaxLength: 1000,
          mqttReconnectTime: 15000,
          serialReconnectTime: 15000,
        }
    entrypoint: >
      /bin/sh -c '
        echo -n "$$DOCKER_NODERED_CONFIG" > /data/settings.js &&
        chown node-red:node-red /data/settings.js &&
        chmod 600 /data/settings.js &&
        exec ./entrypoint.sh
      '
    ports:
      - 1880:1880
      - 502:502 # modbus
    networks:
      - optanet
    volumes:
      - nodered_data:/data
    depends_on:
      - mosquitto
      - influxdb
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/1880' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s 
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
networks:
  optanet:
volumes:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
  influxdb_etc:
  influxdb_lib:
  nodered_data:
